eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# JWT Mapping keys
jwt:
  secret: your_jwt_secret
  expiration: 1800000

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always